<?php

namespace Celibattante\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengeLaunchedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeLaunchedRepository extends EntityRepository
{
}
